---
# tasks file for clear_assets

- name: Clean Assets in project
  shell:
    cmd: /usr/bin/scl enable {{ ruby_version }} 'RAILS_ENV={{rails_env}} bundle exec rake assets:clean'
    chdir: "{{ dir_project }}"

- name: Clobber Assets in project
  shell:
    cmd: /usr/bin/scl enable {{ ruby_version }} 'RAILS_ENV={{rails_env}} bundle exec rake assets:clobber'
    chdir: "{{ dir_project }}"
